# Generated by Django 2.2.7 on 2019-11-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudtest', '0002_auto_20191119_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
