# Generated by Django 2.2.7 on 2019-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('sandwich', models.TextField()),
                ('bread', models.TextField()),
                ('size', models.CharField(max_length=10)),
                ('source', models.TextField()),
            ],
        ),
    ]
