# Generated by Django 2.2.7 on 2019-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_subway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subway',
            name='date',
            field=models.TextField(),
        ),
    ]
